/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * jpquiz
 * OpenAPI spec version: 0.1.0
 */

export type GameMode = (typeof GameMode)[keyof typeof GameMode];

export const GameMode = {
  engtokana: 'engtokana',
  engtokanji: 'engtokanji',
  kanatokanji: 'kanatokanji',
  kanatoeng: 'kanatoeng',
  kanjitokana: 'kanjitokana',
  kanjitoeng: 'kanjitoeng',
} as const;
