/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * jpquiz
 * OpenAPI spec version: 0.1.0
 */
import type { FreeResponseQuestion } from './freeResponseQuestion';

export type GetFreeResponse200 = {
  data: FreeResponseQuestion[];
};
