/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * jpquiz
 * OpenAPI spec version: 0.1.0
 */
import type { GameMode } from './gameMode';
import type { NLevelDto } from './nLevelDto';
import type { PartOfSpeechCategoryDto } from './partOfSpeechCategoryDto';

export type GetGameParams = {
  mode: GameMode;
  levels: NLevelDto[];
  pos: PartOfSpeechCategoryDto[];
};
