/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * jpquiz
 * OpenAPI spec version: 0.1.0
 */

export * from './gameMode';
export * from './getGame200';
export * from './getGameParams';
export * from './multiChoiceQuestion';
export * from './nLevelDto';
export * from './partOfSpeechCategoryDto';
export * from './senseDto';
export * from './wordDto';
