/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * jpquiz
 * OpenAPI spec version: 0.1.0
 */
import type { WordDto } from './wordDto';

export interface MultiChoiceQuestion {
  /** @minimum 0 */
  answer_idx: number;
  choices: string[];
  prompt: string;
  word_pair: WordDto;
}
