/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * jpquiz
 * OpenAPI spec version: 0.1.0
 */

export type NLevelDto = (typeof NLevelDto)[keyof typeof NLevelDto];

export const NLevelDto = {
  N1: 'N1',
  N2: 'N2',
  N3: 'N3',
  N4: 'N4',
  N5: 'N5',
} as const;
