/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * jpquiz
 * OpenAPI spec version: 0.1.0
 */
import type { NLevelDto } from './nLevelDto';
import type { SenseDto } from './senseDto';

export interface WordDto {
  id: string;
  kana: string;
  /** @nullable */
  kanji?: string | null;
  level: NLevelDto;
  senses: SenseDto[];
}
